#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCHEME_PATH="$ROOT_DIR/HAYFHealthKitPrototype.xcodeproj/xcshareddata/xcschemes/HAYF Local LangGraph.xcscheme"
FORTE_DEV_SCHEME_PATH="$ROOT_DIR/HAYFHealthKitPrototype.xcodeproj/xcshareddata/xcschemes/Forte Dev.xcscheme"
ENV_EXAMPLE="$ROOT_DIR/supabase/.env.local-langgraph.example"
ENV_FILE="$ROOT_DIR/supabase/.env.local-langgraph"
SOURCE_OPENAI_ENV="$ROOT_DIR/supabase/.env.local"

LOCAL_EMAIL="${HAYF_LOCAL_AUTH_EMAIL:-local-langgraph@hayf.dev}"
LOCAL_PASSWORD="${HAYF_LOCAL_AUTH_PASSWORD:-local-langgraph-password}"

echo "Checking local Supabase status..."
STATUS_OUTPUT="$(cd "$ROOT_DIR" && npx supabase status -o env)"

status_value() {
  local candidate raw value
  for candidate in "$@"; do
    raw="$(printf '%s\n' "$STATUS_OUTPUT" | sed 's/^export //' | awk -F= -v key="$candidate" '$1 == key { print substr($0, index($0, "=") + 1); exit }')"
    value="${raw%\"}"
    value="${value#\"}"
    if [ -n "$value" ]; then
      printf '%s' "$value"
      return 0
    fi
  done
  return 1
}

SUPABASE_URL="$(status_value SUPABASE_URL API_URL || true)"
SUPABASE_ANON_KEY="$(status_value SUPABASE_ANON_KEY ANON_KEY || true)"
SUPABASE_SERVICE_ROLE_KEY="$(status_value SUPABASE_SERVICE_ROLE_KEY SERVICE_ROLE_KEY || true)"

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ] || [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
  echo "Could not read local Supabase URL/keys. Start Docker and run: npx supabase start" >&2
  echo "$STATUS_OUTPUT" >&2
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  cp "$ENV_EXAMPLE" "$ENV_FILE"
fi

OPENAI_API_KEY_VALUE=""
if [ -f "$SOURCE_OPENAI_ENV" ]; then
  OPENAI_API_KEY_VALUE="$(awk -F= '$1 == "OPENAI_API_KEY" { print substr($0, index($0, "=") + 1); exit }' "$SOURCE_OPENAI_ENV")"
fi

python3 - "$ENV_FILE" "$OPENAI_API_KEY_VALUE" "$SUPABASE_URL" "$SUPABASE_ANON_KEY" "$LOCAL_EMAIL" "$LOCAL_PASSWORD" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
openai_key = sys.argv[2]
supabase_url = sys.argv[3]
supabase_anon_key = sys.argv[4]
local_email = sys.argv[5]
local_password = sys.argv[6]
values = {}
for line in path.read_text().splitlines():
    if "=" in line and not line.lstrip().startswith("#"):
        key, value = line.split("=", 1)
        values[key] = value

if openai_key and not values.get("OPENAI_API_KEY"):
    values["OPENAI_API_KEY"] = openai_key

defaults = {
    "SUPABASE_URL": supabase_url,
    "SUPABASE_ANON_KEY": supabase_anon_key,
    "HAYF_LOCAL_AUTH_EMAIL": local_email,
    "HAYF_LOCAL_AUTH_PASSWORD": local_password,
    "OPENAI_MODEL": "gpt-5-mini",
    "ATHLETE_PROFILE_ENGINE_URL": "http://host.docker.internal:54321/functions/v1/athlete-profile-engine",
    "ATHLETE_PROFILE_ENGINE_API_KEY": "local-athlete-profile-engine-dev",
    "ATHLETE_PROFILE_ENGINE_TIMEOUT_MS": "10000",
    "TRAINING_ORCHESTRATOR_URL": "http://host.docker.internal:8787",
    "TRAINING_ORCHESTRATOR_API_KEY": "local-langgraph-dev",
    "TRAINING_ORCHESTRATOR_REQUIRED": "true",
}
for key, value in defaults.items():
    values.setdefault(key, value)

lines = [
    "# Generated by tools/local-langgraph/setup-local-langgraph.sh",
    "# Real secrets stay local and are ignored by git.",
]
for key in ["OPENAI_API_KEY", "OPENAI_MODEL", "SUPABASE_URL", "SUPABASE_ANON_KEY", "HAYF_LOCAL_AUTH_EMAIL", "HAYF_LOCAL_AUTH_PASSWORD", "ATHLETE_PROFILE_ENGINE_URL", "ATHLETE_PROFILE_ENGINE_API_KEY", "ATHLETE_PROFILE_ENGINE_TIMEOUT_MS", "TRAINING_ORCHESTRATOR_URL", "TRAINING_ORCHESTRATOR_API_KEY", "TRAINING_ORCHESTRATOR_REQUIRED"]:
    lines.append(f"{key}={values.get(key, '')}")
path.write_text("\n".join(lines) + "\n")
PY

python3 - "$SCHEME_PATH" "$FORTE_DEV_SCHEME_PATH" "$SUPABASE_URL" "$SUPABASE_ANON_KEY" "$LOCAL_EMAIL" "$LOCAL_PASSWORD" <<'PY'
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

scheme_paths = [Path(sys.argv[1]), Path(sys.argv[2])]
values = {
    "HAYF_SUPABASE_URL": sys.argv[3],
    "HAYF_SUPABASE_ANON_KEY": sys.argv[4],
    "HAYF_LOCAL_AUTH_EMAIL": sys.argv[5],
    "HAYF_LOCAL_AUTH_PASSWORD": sys.argv[6],
    "HAYF_LOCAL_LANGGRAPH": "true",
}

for scheme_path in scheme_paths:
    tree = ET.parse(scheme_path)
    root = tree.getroot()
    launch = root.find("LaunchAction")
    if launch is None:
        raise SystemExit(f"LaunchAction not found in {scheme_path}")
    env = launch.find("EnvironmentVariables")
    if env is None:
        env = ET.SubElement(launch, "EnvironmentVariables")

    existing = {item.attrib.get("key"): item for item in env.findall("EnvironmentVariable")}
    for key, value in values.items():
        item = existing.get(key)
        if item is None:
            item = ET.SubElement(env, "EnvironmentVariable")
        item.set("key", key)
        item.set("value", value)
        item.set("isEnabled", "YES")

    ET.indent(tree, space="   ")
    tree.write(scheme_path, encoding="UTF-8", xml_declaration=True)
PY

echo "Ensuring local dev auth user exists..."
BODY="{\"email\":\"$LOCAL_EMAIL\",\"password\":\"$LOCAL_PASSWORD\",\"email_confirm\":true,\"user_metadata\":{\"full_name\":\"Local LangGraph Dev\"}}"
RESPONSE_FILE="$(mktemp)"
HTTP_STATUS="$(curl -sS -o "$RESPONSE_FILE" -w "%{http_code}" \
  -X POST "$SUPABASE_URL/auth/v1/admin/users" \
  -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
  -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
  -H "Content-Type: application/json" \
  --data "$BODY")"

if [ "$HTTP_STATUS" != "200" ] && [ "$HTTP_STATUS" != "201" ] && [ "$HTTP_STATUS" != "422" ]; then
  cat "$RESPONSE_FILE" >&2
  rm -f "$RESPONSE_FILE"
  exit 1
fi
rm -f "$RESPONSE_FILE"

echo "Local LangGraph setup is ready."
echo "Scheme: HAYF Local LangGraph"
echo "Supabase URL: $SUPABASE_URL"
echo "Local auth user: $LOCAL_EMAIL"
